import Head from 'next/head';
import Login from '@/components/layouts/Login';
import { getProviders, signIn } from "next-auth/react";

export default function login({providers}) {
  return (
    <>
      <Head>
        <title>Doctor App | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Login providers={providers} signIn={signIn} />
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  const providers = await getProviders()
  return {
    props: { providers },
  }
}