import Head from 'next/head';
import { useSession, signIn, signOut } from 'next-auth/react';
import SignUp from '@/components/layouts/SignUp';

export default function signUp() {
  return (
    <>
      <Head>
        <title>Doctor App | Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SignUp/>
      </main>
    </>
  )
}
